sudo: false
language: python
cache: pip
python:
- 2.7
- 3.4
- 3.5
- 3.6
install: pip install tox-travis
script: tox
after_success:
- coveralls
deploy:
  provider: pypi
  user: jazzband
  server: https://jazzband.co/projects/django-axes/upload
  distributions: sdist bdist_wheel
  password:
    secure: TCH5tGIggL2wsWce2svMwpEpPiwVOYqq1R3uSBTexszleP0OafNq/wZk2KZEReR5w1Aq68qp5F5Eeh2ZjJTq4f9M4LtTvqQzrmyNP55DYk/uB1rBJm9b4gBgMtAknxdI2g7unkhQEDo4suuPCVofM7rrDughySNpmvlUQYDttHQ=
  on:
    tags: true
    repo: jazzband/django-axes
    python: 3.6
