coverage:
  status:
    patch: off
    project:
      default:
        # Minimum test coverage required for pass
        target: 80%
        # Maximum test coverage change allowed for pass
        threshold: 20%
